/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe01;

import javax.swing.JOptionPane;

/**
 *
 * @author lucanthony
 */
public class Tictactoe extends javax.swing.JFrame {

    /**
     * Creates new form Tictactoe
     */
    int turn = 2;  // this variable allows players to play once at the time.
    
    int buttonUsed [] = {0, 0, 0, 0, 0, 0, 0, 0, 0}; // this array represent the number of  buttons on my tictactoe board
    
    int p1Won [] = {0, 0, 0, 0, 0, 0, 0, 0, 0}; // Since tictatoe is 2 player game, and there no even cases, there can only be one winner.
    
    int p2Won [] = {0, 0, 0, 0, 0, 0, 0, 0, 0}; // if you read the previous comment  you  know that between player 1 and player 2 only one of them can win the game.
    
// this function allows us to identify the winner cases scenarios
// this tictactoe board is like  a 3 by 3 matrix of X's and O's. 
// The player who succeeds in placing three of their marks in a horizontal, 
// vertical, or diagonal row is the winner.
        
    
      int p1Won() 
          {
            if(p1Won[0] == 1  &&  p1Won[1] == 1  &&  p1Won[2]==1)
            {
                return 1;
            }
            
             if(p1Won[3] == 1  &&  p1Won[4] == 1  &&  p1Won[5]==1)
            {
                return 1;
            }
             
              if(p1Won[6] == 1  &&  p1Won[7] == 1  &&  p1Won[8]==1)
            {
                return 1;
            }
              
               if(p1Won[0] == 1  &&  p1Won  [3] == 1  &&  p1Won[6]==1)
            {
                return 1;
            }
               
                if(p1Won[1] == 1  &&  p1Won[4] == 1  &&  p1Won[7]==1)
            {
                return 1;
            }
                
                 if(p1Won[2] == 1  &&  p1Won  [5] == 1  &&  p1Won[8]==1)
            {
                return 1;
            }
                 
                  if(p1Won[2] == 1  &&  p1Won  [4] == 1  &&  p1Won[6]==1)
            {
                return 1;
            }
                  
                   if(p1Won[0] == 1  &&  p1Won  [4] == 1  &&  p1Won[8]==1)
            {
                return 1;
            }
                   
                return 0; // return FALSE
        }
      
      
      
//this function allows us to identify the winner cases scenarios
// this tictactoe board is like  a 3 by 3 matrix of X's and O's. 
// The player who succeeds in placing three of their marks in a horizontal, 
// vertical, or diagonal row is the winner.
      int p2Won() 
          {
            if(p2Won[0] == 1  &&  p2Won[1] == 1  &&  p2Won[2]==1)
            {
                return 1;
            }
            
             if(p2Won[3] == 1  &&  p2Won[4] == 1  &&  p2Won[5]==1)
            {
                return 1;
            }
             
              if(p2Won[6] == 1  &&  p2Won[7] == 1  &&  p2Won[8]==1)
            {
                return 1;
            }
              
               if(p2Won[0] == 1  &&  p2Won  [3] == 1  &&  p2Won[6]==1)
            {
                return 1;
            }
               
                if(p2Won[1] == 1  &&  p2Won[4] == 1  &&  p2Won[7]==1)
            {
                return 1;
            }
                
                 if(p2Won[2] == 1  &&  p2Won  [5] == 1  &&  p2Won[8]==1)
            {
                return 1;
            }
                 
                  if(p2Won[2] == 1  &&  p2Won  [4] == 1  &&  p2Won[6]==1)
            {
                return 1;
            }
                  
                   if(p2Won[0] == 1  &&  p2Won  [4] == 1  &&  p2Won[8]==1)
            {
                return 1;
            }
                   
                return 0; // return FALSE
        }
      
    
    public Tictactoe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b2.setFont(new java.awt.Font("Skia", 1, 48)); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setFont(new java.awt.Font("Skia", 1, 48)); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b5.setFont(new java.awt.Font("Skia", 1, 48)); // NOI18N
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b1.setFont(new java.awt.Font("Skia", 1, 48)); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b6.setFont(new java.awt.Font("Skia", 1, 48)); // NOI18N
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b7.setFont(new java.awt.Font("Skia", 1, 48)); // NOI18N
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b4.setFont(new java.awt.Font("Skia", 1, 48)); // NOI18N
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b9.setFont(new java.awt.Font("Skia", 1, 48)); // NOI18N
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b8.setFont(new java.awt.Font("Skia", 1, 48)); // NOI18N
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        reset.setFont(new java.awt.Font("Skia", 1, 24)); // NOI18N
        reset.setText("Play Again");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(b8, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addGap(52, 52, 52)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reset)
                .addGap(181, 181, 181))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed

if(buttonUsed [1] == 0)
 {
        if(turn % 2 == 0)
        {
        turn ++;
        b2.setText("X");
        buttonUsed [1] = 1;
        p1Won [1] = 1;
        
        
        int result1 = p1Won();
        int result2 = p2Won();
        
        if(result1 == 1)
            {
                
                JOptionPane.showMessageDialog(rootPane, "!**Player 1 is the winner**!");
            }
        else if (result2 == 1)
            {
                JOptionPane.showMessageDialog(rootPane, "!**Player 2 is the winner**!");
            }
        
        
         }// TODO add your handling code here:
        else
         {
         turn ++;
         b2.setText("O");
         buttonUsed [1] = 1;
         p2Won [1] = 1;
         
         
         int result1 = p1Won();
         int result2 = p2Won();
        
        if(result1 == 1)
            {
                
                JOptionPane.showMessageDialog(rootPane, "!**Player 1 is the winner**!");
            }
        else if (result2 == 1)
            {
                JOptionPane.showMessageDialog(rootPane, "!**Player 2 is the winner**!");
            }
     }
 }
else {
        JOptionPane.showMessageDialog(rootPane, "!This button is already in use!");
      }      // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed

if(buttonUsed [2] == 0)
 {
        if(turn % 2 == 0)
        {
        turn ++;
        b3.setText("X");
        buttonUsed [2] = 1;
        p1Won [2] = 1;
        
        
        int result1 = p1Won();
        int result2 = p2Won();
        
        if(result1 == 1)
            {
                
                JOptionPane.showMessageDialog(rootPane, "!**Player 1 is the winner**!");
            }
        else if (result2 == 1)
            {
                JOptionPane.showMessageDialog(rootPane, "!**Player 2 is the winner**!");
            }
        
         }// TODO add your handling code here:
        else
         {
         turn ++;
         b3.setText("O");
         buttonUsed [2] = 1;
         p2Won [2] = 1;
         
         
         int result1 = p1Won();
        int result2 = p2Won();
        
        if(result1 == 1)
            {
                
                JOptionPane.showMessageDialog(rootPane, "!**Player 1 is the winner**!");
            }
        else if (result2 == 1)
            {
                JOptionPane.showMessageDialog(rootPane, "!**Player 2 is the winner**!");
            }
     }
 }
else {
        JOptionPane.showMessageDialog(rootPane, "!This button is already in use!");
      }
// TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
    
if(buttonUsed [4] == 0)
 {
        if(turn % 2 == 0)
        {
        turn ++;
        b5.setText("X");
        buttonUsed [4] = 1;
        p1Won [4] = 1;
        
        
        int result1 = p1Won();
        int result2 = p2Won();
        
        if(result1 == 1)
            {
                
                JOptionPane.showMessageDialog(rootPane, "!**Player 1 is the winner**!");
            }
        else if (result2 == 1)
            {
                JOptionPane.showMessageDialog(rootPane, "!**Player 2 is the winner**!");
            }
        
         }// TODO add your handling code here:
        else
         {
         turn ++;
         b5.setText("O");
         buttonUsed [4] = 1;
         p2Won [4] = 1;
         
         
         int result1 = p1Won();
        int result2 = p2Won();
        
        if(result1 == 1)
            {
                
                JOptionPane.showMessageDialog(rootPane, "!**Player 1 is the winner**!");
            }
        else if (result2 == 1)
            {
                JOptionPane.showMessageDialog(rootPane, "!**Player 2 is the winner**!");
            }
        
            }
            }
        else {
        JOptionPane.showMessageDialog(rootPane, "!This button is already in use!");
        }      // TODO add your handling code here:
    }//GEN-LAST:event_b5ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed

if(buttonUsed [0] == 0)
 {
        if(turn % 2 == 0)
        {
        turn ++;
        b1.setText("X");
        buttonUsed [0] = 1;
        p1Won [0] = 1;
        int result1 = p1Won();
        int result2 = p2Won();
        
        if(result1 == 1)
            {
                
                JOptionPane.showMessageDialog(rootPane, "!**Player 1 is the winner**!");
            }
        else if (result2 == 1)
            {
                JOptionPane.showMessageDialog(rootPane, "!**Player 2 is the winner**!");
            }
        
         }// TODO add your handling code here:
        else
         {
         turn ++;
         b1.setText("O");
         buttonUsed [0] = 1;
         p2Won [0] = 1;
         
         int result1 = p1Won();
         int result2 = p2Won();
        
        if(result1 == 1)
            {
                
                JOptionPane.showMessageDialog(rootPane, "!**Player 1 is the winner**!");
            }
        else if (result2 == 1)
            {
                JOptionPane.showMessageDialog(rootPane, "!**Player 2 is the winner**!");
            }
     }
 }
/*else {
        JOptionPane.showMessageDialog(rootPane, "!This button is already in use!");
      }

    if(turn % 2 == 0)
    {
        turn ++;
        b1.setText("X");
        buttonUsed [0] = 1;
        
    }// TODO add your handling code here:
    else
    {
    turn ++;
    b1.setText("O");
    buttonUsed [0] = 1;
    }
*/
    }//GEN-LAST:event_b1ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
if(buttonUsed [5] == 0)
 {
        if(turn % 2 == 0)
        {
        turn ++;
        b6.setText("X");
        buttonUsed [5] = 1;
        p1Won[5] = 1;
        
        int result1 = p1Won();
        int result2 = p2Won();
        
        if(result1 == 1)
            {
                
                JOptionPane.showMessageDialog(rootPane, "!**Player 1 is the winner**!");
            }
        else if (result2 == 1)
            {
                JOptionPane.showMessageDialog(rootPane, "!**Player 2 is the winner**!");
            }
        
         }// TODO add your handling code here:
        else
         {
         turn ++;
         b6.setText("O");
         buttonUsed [5] = 1;
         p2Won[5] = 1;
         int result1 = p1Won();
        int result2 = p2Won();
        
        if(result1 == 1)
            {
                
                JOptionPane.showMessageDialog(rootPane, "!**Player 1 is the winner**!");
            }
        else if (result2 == 1)
            {
                JOptionPane.showMessageDialog(rootPane, "!**Player 2 is the winner**!");
            }
            }
            }
        else {
        JOptionPane.showMessageDialog(rootPane, "!This button is already in use!");
             }        // TODO add your handling code here:
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
    if(buttonUsed [6] == 0)
 {
        if(turn % 2 == 0)
        {
        turn ++;
        b7.setText("X");
        buttonUsed [6] = 1;
        p1Won [6] = 1;
        
        int result1 = p1Won();
        int result2 = p2Won();
        
        if(result1 == 1)
            {
                
                JOptionPane.showMessageDialog(rootPane, "!**Player 1 is the winner**!");
            }
        else if (result2 == 1)
            {
                JOptionPane.showMessageDialog(rootPane, "!**Player 2 is the winner**!");
            }
        
         }// TODO add your handling code here:
        else
         {
         turn ++;
         b7.setText("O");
         buttonUsed [6] = 1;
         p2Won[6] = 1;
         
         int result1 = p1Won();
         int result2 = p2Won();
        
        if(result1 == 1)
            {
                
                JOptionPane.showMessageDialog(rootPane, "!**Player 1 is the winner**!");
            }
        else if (result2 == 1)
            {
                JOptionPane.showMessageDialog(rootPane, "!**Player 2 is the winner**!");
            }
     }
 }
else {
        JOptionPane.showMessageDialog(rootPane, "!This button is already in use!");
      }        // TODO add your handling code here:
    }//GEN-LAST:event_b7ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
    
    if(buttonUsed [3] == 0)
 {
        if(turn % 2 == 0)
        {
        turn ++;
        b4.setText("X");
        buttonUsed [3] = 1;
        p1Won[3] = 1;
        
        int result1 = p1Won();
        int result2 = p2Won();
        
        if(result1 == 1)
            {
                
                JOptionPane.showMessageDialog(rootPane, "!**Player 1 is the winner**!");
            }
        else if (result2 == 1)
            {
                JOptionPane.showMessageDialog(rootPane, "!**Player 2 is the winner**!");
            }
        
         }// TODO add your handling code here:
        else
         {
         turn ++;
         b4.setText("O");
         buttonUsed [3] = 1;
         p2Won[3] = 1;
         
         int result1 = p1Won();
         int result2 = p2Won();
        
        if(result1 == 1)
            {
                
                JOptionPane.showMessageDialog(rootPane, "!**Player 1 is the winner**!");
            }
        else if (result2 == 1)
            {
                JOptionPane.showMessageDialog(rootPane, "!**Player 2 is the winner**!");
            }
         }
         }
        else {
        JOptionPane.showMessageDialog(rootPane, "!This button is already in use!");
         }      // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
    if(buttonUsed [8] == 0)
 {
        if(turn % 2 == 0)
        {
        turn ++;
        b9.setText("X");
        buttonUsed [8] = 1;
        p1Won[8] = 1;
        
        int result1 = p1Won();
        int result2 = p2Won();
        
        if(result1 == 1)
            {
                
                JOptionPane.showMessageDialog(rootPane, "!**Player 1 is the winner**!");
            }
        else if (result2 == 1)
            {
                JOptionPane.showMessageDialog(rootPane, "!**Player 2 is the winner**!");
            }
        
         }// TODO add your handling code here:
        else
         {
         turn ++;
         b9.setText("O");
         buttonUsed [8] = 1;
         p2Won[8] = 1;
         int result1 = p1Won();
        int result2 = p2Won();
        
        if(result1 == 1)
            {
                
                JOptionPane.showMessageDialog(rootPane, "!**Player 1 is the winner**!");
            }
        else if (result2 == 1)
            {
                JOptionPane.showMessageDialog(rootPane, "!**Player 2 is the winner**!");
            }
         }
         }
        else {
        JOptionPane.showMessageDialog(rootPane, "!This button is already in use!");
          }      // TODO add your handling code here:
    }//GEN-LAST:event_b9ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
   if(buttonUsed [7] == 0)
 {
        if(turn % 2 == 0)
        {
        turn ++;
        b8.setText("X");
        buttonUsed [7] = 1;
        p1Won[7] = 1;
        
        int result1 = p1Won();
        int result2 = p2Won();
        
        if(result1 == 1)
            {
                
                JOptionPane.showMessageDialog(rootPane, "!**Player 1 is the winner**!");
            }
        else if (result2 == 1)
            {
                JOptionPane.showMessageDialog(rootPane, "!**Player 2 is the winner**!");
            }
        
         }// TODO add your handling code here:
        else
         {
         turn ++;
         b8.setText("O");
         buttonUsed [7] = 1;
         p2Won[7] = 1;
         
         
         int result1 = p1Won();
        int result2 = p2Won();
        
        if(result1 == 1)
            {
                
                JOptionPane.showMessageDialog(rootPane, "!**Player 1 is the winner**!");
            }
        else if (result2 == 1)
            {
                JOptionPane.showMessageDialog(rootPane, "!**Player 2 is the winner**!");
            }
         }
         }
        else {
        JOptionPane.showMessageDialog(rootPane, "!This button is already in use!");
        }    // TODO add your handling code here:
    }//GEN-LAST:event_b8ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
        
        
        turn = 2;
        
        for (int i = 0; i < 9; i++)
            
        {
            buttonUsed [i] = 0;
        }
        
        for (int i = 0; i < 9; i++)
            
        {
            p1Won [i] = 0;
        }
        
        for (int i = 0; i < 9; i++)
            
        {
            p2Won [i] = 0;
        }
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tictactoe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
